"""empty message

Revision ID: 91b2eb6ed6be
Revises: d04202f4d7cc
Create Date: 2021-04-09 14:02:32.144409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91b2eb6ed6be'
down_revision = 'd04202f4d7cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('roomtype', sa.String(length=150), nullable=True))
    op.drop_column('room', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('type', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_column('room', 'roomtype')
    # ### end Alembic commands ###
