"""empty message

Revision ID: b637b9c65172
Revises: edb612b6d3d6
Create Date: 2021-04-09 13:40:28.471537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b637b9c65172'
down_revision = 'edb612b6d3d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('roomtype', sa.String(length=150), nullable=True))
    op.drop_column('room', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('type', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_column('room', 'roomtype')
    # ### end Alembic commands ###
