"""empty message

Revision ID: d04202f4d7cc
Revises: b637b9c65172
Create Date: 2021-04-09 13:59:51.765784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd04202f4d7cc'
down_revision = 'b637b9c65172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('roomtype', sa.String(length=150), nullable=True))
    op.drop_column('room', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('type', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_column('room', 'roomtype')
    # ### end Alembic commands ###
